### ISSUE TITLE
Problem in installing

### ISSUE THREAD

**Issue by dong-y** [tidepool-org/tideline#211]
Hi when I try to install it, there is an error:
- npm WARN install Refusing to install tideline as a dependency of itself

**Comment by jebeck** [comment]
It sounds like you've cloned tideline and you're trying to install tideline as a dependency of itself. This was a bit unclear in the README - I tried to clarify it a bit. tideline is Tidepool's data visualization library, which we use in our web application [blip](https://github.com/tidepool-org/blip). It is published to the [npm](https://www.npmjs.com/) package repository for convenient installation into other projects like blip. When you are installing tideline for use in another application (like blip), you should use the command `npm install --save tideline`. If you've cloned tideline because you're interested in contributing to its development and you want to run tideline's mini example application (which is solely for development purposes), you just use `npm install` to install tideline's dependencies, and `npm start` to run the example application. If you'd like to help clarify this further in the README, feel free to fork and submit a PR.
